#!/usr/bin/python

import sys
import os
import pprint

filename = sys.argv[1]

content = []

def searchIP():
	listIp = []
	for line in content:
		IP = line.split('|')[4]
		listIp.append(IP)
	return listIp	


def searchRepo():
	listRepo = []
	for line in content:
		repo = line.split('|')[5].split(':')[0]
		listRepo.append(repo)
	return listRepo

def searchDate():
	listDate = []
	for line in content:
		date = line.split('|')[0][:8]
		listDate.append(date)
	return listDate

def dateUsage(listDate):
	dataDict = {}
	for items in listDate:
		dataSize = 0
		for line in content:
			if (items == line.split('|')[0][:8]):
				dataSize = dataSize + int(line.split('|')[6])
		dataDict.update({items:dataSize})
	return dataDict

def repoUsage(listRepo):
	dataDict = {}
	for items in listRepo:
		dataSize = 0
		for line in content:
			if(items == line.split('|')[5].split(':')[0]):
				dataSize = dataSize + int(line.split('|')[6])
		dataDict.update({items:dataSize})
	return dataDict

def ipUsage(listIp):
	dataDict = {}
	for items in listIp:
		dataSize = 0
		for line in content:
			if (items == line.split('|')[4]):
				dataSize = dataSize + int(line.split('|')[6])
		dataDict.update({items:dataSize})
	return dataDict	

def ipRepoComb(listIp,listRepo):
	listComb = []
	for x, y in [(x,y) for x in listIp for y in listRepo]:
		string = x + "," + y
		listComb.append(string)
	return listComb

def ipRepoUsage(listComb):
	dataDict = {}
	for items in listComb:
		dataSize = 0
		itemsplit = items.split(',')
		addr = itemsplit[0].strip()
		reps = itemsplit[1].strip()
		for line in content:
			if line.split('|')[4] == addr and line.split('|')[5].split(':')[0] == reps:
				dataSize = dataSize + int(line.split('|')[6])
		dataDict.update({items:dataSize})
	return dataDict

def remove_duplicates(l):
    return list(set(l))

with open(filename) as f:
    content = f.readlines()

listIp = remove_duplicates(searchIP())
listRepo = remove_duplicates(searchRepo())
listDate = remove_duplicates(searchDate())
listComb = ipRepoComb(listIp,listRepo)

repoUsage = repoUsage(listRepo)
ipUsage = ipUsage(listIp)
dateUsage = dateUsage(listDate)
ipRepoUsage = ipRepoUsage(listComb)


#repoUsage(listRepo)
#print (listIp)
#print (listRepo)
#print (listDate)
#print (listComb)

#print (repoUsage)
#print (ipUsage)
#print (ipRepoUsage)

print("Below is the usage on each date:")
print("###########################################################################################################")
pprint.pprint(dateUsage)
print("################################")
print("Below is the usage per repository:")
print("################################")
pprint.pprint( repoUsage)
print("################################")
print("Below is the usage per IP:")
print("################################")
pprint.pprint(ipUsage)
print("################################")
print("Below is the usage per IP and Repo:")
print("################################")
pprint.pprint(ipRepoUsage)
print("################################")

